FROM python:3.11-slim   

WORKDIR /app    

COPY Backend/requirements.txt . 
RUN pip install --no-cache-dir -r requirements.txt  

COPY Backend/ . 

EXPOSE 5000 

CMD ["gunicorn", "--bind", "0.0.0.0:5000", "app:app"]   